/* --- ASTRALIS ZOO - JAVASCRIPT --- */

const zooData = {
    mamalia: {
        title: "Dunia Mamalia",
        desc: "Temukan keajaiban hewan menyusui yang luar biasa dari berbagai habitat.",
        animals: [
            { name: "Harimau Benggala", emoji: "🐅", fact: "Harimau terbesar di dunia dengan belang unik pada setiap individunya.", diet: "Daging (Karnivora)", habitat: "Hutan & Padang Rumput Asia Selatan", reproduksi: "Melahirkan 2–4 anak setelah masa kehamilan ±105 hari. Anak diasuh ibu selama 2–3 tahun." },
            { name: "Harimau Sumatera", emoji: "🐯", fact: "Harimau terkecil yang masih ada, mereka adalah perenang hebat yang sangat suka air!", diet: "Daging (Karnivora)", habitat: "Hutan Hujan Tropis Sumatera", reproduksi: "Masa kehamilan ±103 hari, melahirkan 2–3 anak. Termasuk satwa kritis terancam punah." },
            { name: "Singa", emoji: "🦁", fact: "Satu-satunya kucing besar yang hidup dalam kelompok sosial besar bernama Pride.", diet: "Daging", habitat: "Sabana Afrika", reproduksi: "Masa kehamilan ±110 hari, melahirkan 1–4 anak. Betina dalam satu pride sering melahirkan bersamaan." },
            { name: "Serval", emoji: "🐆", fact: "Memiliki telinga terbesar relatif terhadap ukuran tubuh di antara semua jenis kucing.", diet: "Burung & Hewan Kecil", habitat: "Savana & Rawa Afrika", reproduksi: "Masa kehamilan ±74 hari, melahirkan 1–4 anak. Anak disapih pada usia 5 bulan." },
            { name: "Caracal", emoji: "🐱", fact: "Mampu melompat 3 meter ke udara untuk menangkap burung yang sedang terbang.", diet: "Burung & Mamalia Kecil", habitat: "Savana & Semi-Arid Afrika–Asia", reproduksi: "Masa kehamilan ±78 hari, melahirkan 1–6 anak. Anak mulai mandiri pada usia 9–10 bulan." },
            { name: "Puma", emoji: "🦁", fact: "Kucing besar dengan sebaran paling luas di dunia, dari Kanada hingga Patagonia.", diet: "Rusa & Mamalia Besar", habitat: "Hutan, Pegunungan & Padang Amerika", reproduksi: "Masa kehamilan ±92 hari, melahirkan 1–6 anak. Anak berbintik saat lahir dan kehilangan bintik setelah 6 bulan." },
            { name: "Kuwuk", emoji: "🐈", fact: "Kucing liar terkecil asli Asia Tenggara yang aktif berburu di malam hari.", diet: "Hewan Kecil & Serangga", habitat: "Hutan Tropis Asia Tenggara", reproduksi: "Masa kehamilan ±65–70 hari, melahirkan 2–4 anak. Hidup soliter dan sangat teritorial." },
            { name: "Beruang Madu", emoji: "🐻", fact: "Beruang terkecil di dunia, asli Asia Tenggara, dengan lidah panjang untuk menjilat madu.", diet: "Madu, Buah & Serangga", habitat: "Hutan Hujan Tropis Asia Tenggara", reproduksi: "Masa kehamilan ±95 hari, melahirkan 1–2 anak (±300 gram). Anak menyusu selama 18 bulan." },
            { name: "Landak Jawa", emoji: "🦔", fact: "Duri landak sebenarnya adalah rambut yang mengeras, bukan tulang, dan bisa tumbuh kembali.", diet: "Akar, Umbi & Buah", habitat: "Hutan & Semak Asia", reproduksi: "Masa kehamilan ±112 hari, melahirkan 1–4 anak. Anak lahir dengan duri lunak yang mengeras dalam beberapa jam." },
            { name: "Owa Jawa", emoji: "🐒", fact: "Suara Owa Jawa bisa terdengar hingga jarak 1 km sebagai penanda wilayah.", diet: "Buah & Daun", habitat: "Hutan Jawa", reproduksi: "Melahirkan 1 anak setelah masa kehamilan ±7 bulan. Monogami sejati, pasangan hidup seumur hidup." },
            { name: "Siamang", emoji: "🦧", fact: "Memiliki kantung tenggorokan besar yang mengembang sebesar kepala untuk memperkuat suara.", diet: "Buah, Daun & Serangga", habitat: "Hutan Sumatera & Malaysia", reproduksi: "Masa kehamilan ±7–8 bulan, melahirkan 1 anak tiap 2–3 tahun. Ayah ikut aktif merawat anak." },
            { name: "Ungko", emoji: "🐵", fact: "Primata arboreal yang hampir seluruh hidupnya dihabiskan di atas pohon.", diet: "Buah & Bunga", habitat: "Hutan Sumatera", reproduksi: "Melahirkan 1 anak per kelahiran. Masa asuh panjang hingga 2 tahun sebelum anak benar-benar mandiri." },
            { name: "Orangutan Kalimantan", emoji: "🦧", fact: "Bisa membuat payung dari daun lebar saat hujan, bukti kecerdasan yang luar biasa.", diet: "Buah, Daun & Kulit Pohon", habitat: "Hutan Hujan Kalimantan", reproduksi: "Masa kehamilan ±8,5 bulan. Interval kelahiran terpanjang mamalia darat: 7–9 tahun per anak." },
            { name: "Lutung Jawa", emoji: "🐒", fact: "Bayi lutung lahir dengan bulu oranye mencolok yang berubah gelap setelah 3–4 bulan.", diet: "Daun & Buah", habitat: "Hutan Jawa & Bali", reproduksi: "Masa kehamilan ±6 bulan, melahirkan 1 anak. Seluruh betina dalam kelompok turut merawat bayi." },
            { name: "Monyet Ekor Panjang", emoji: "🐒", fact: "Satu-satunya primata non-manusia yang aktif mencuci makanannya sebelum dimakan.", diet: "Buah, Biji & Serangga", habitat: "Hutan Asia Tenggara", reproduksi: "Masa kehamilan ±162–186 hari, melahirkan 1 anak. Hidup dalam kelompok besar hingga 30 ekor." },
            { name: "Monyet Dare", emoji: "🐒", fact: "Primata endemik Sulawesi yang terancam punah akibat perburuan dan hilangnya habitat.", diet: "Buah & Dedaunan", habitat: "Hutan Sulawesi", reproduksi: "Melahirkan 1 anak per kelahiran. Anak tinggal bersama induk hingga usia 1,5–2 tahun." },
            { name: "Monyet Jepang", emoji: "🐒", fact: "Satu-satunya primata non-manusia yang gemar berendam di onsen saat musim dingin.", diet: "Buah, Biji & Serangga", habitat: "Hutan Jepang", reproduksi: "Masa kehamilan ±173 hari, melahirkan 1 anak. Kebiasaan berendam di onsen dipelajari secara kultural antar generasi." },
            { name: "Chimpanzee", emoji: "🦍", fact: "Berbagi 98,7% DNA dengan manusia dan mampu menggunakan alat bantu untuk memecahkan masalah.", diet: "Buah, Kacang & Daging", habitat: "Hutan Afrika Barat & Tengah", reproduksi: "Masa kehamilan ±8 bulan, melahirkan 1 anak. Anak menyusu hingga 4–5 tahun dan tinggal bersama ibu hingga 10 tahun." },
            { name: "Babun Mantel", emoji: "🐒", fact: "Jantan dewasa memiliki jubah rambut panjang putih keperakan seperti mantel yang megah.", diet: "Omnivora", habitat: "Savana & Tebing Berbatu Afrika", reproduksi: "Masa kehamilan ±6 bulan, melahirkan 1 anak. Jantan melindungi harem betina secara ketat." },
            { name: "Bekantan", emoji: "🐒", fact: "Hidung besar jantan bekantan digunakan untuk menarik betina dan memperkuat suara.", diet: "Daun & Buah", habitat: "Hutan Mangrove Kalimantan", reproduksi: "Masa kehamilan ±166 hari, melahirkan 1 anak. Hidup dalam kelompok satu jantan dengan beberapa betina." },
            { name: "Babi Kutil", emoji: "🐗", fact: "Tidur di liang hewan lain dan masuk mundur agar taringnya menghadap ke luar untuk pertahanan.", diet: "Omnivora", habitat: "Savana Afrika", reproduksi: "Masa kehamilan ±170 hari, melahirkan 2–8 anak. Satu-satunya babi yang beradaptasi di ekosistem padang terbuka." },
            { name: "Babirusa", emoji: "🐗", fact: "Taring atas babirusa menembus kulit moncongnya sendiri dan tumbuh melengkung ke arah kepala.", diet: "Buah, Jamur & Akar", habitat: "Hutan Sulawesi", reproduksi: "Masa kehamilan ±150–157 hari, melahirkan 1–2 anak. Hanya melahirkan 1–2 anak, jauh lebih sedikit dari babi lain." },
            { name: "Banteng Jawa", emoji: "🐂", fact: "Leluhur sapi domestik Bali dan dianggap sakral dalam beberapa budaya Jawa.", diet: "Herbivora (Rumput & Daun)", habitat: "Hutan & Padang Rumput Asia Tenggara", reproduksi: "Masa kehamilan ±285 hari, melahirkan 1 anak. Betina dan anak tinggal dalam kelompok, jantan hidup soliter." },
            { name: "Binturong", emoji: "🦡", fact: "Satu-satunya mamalia Asia dengan ekor prehensil yang bisa mencengkeram seperti tangan.", diet: "Buah & Hewan Kecil", habitat: "Hutan Hujan Asia Tenggara", reproduksi: "Masa kehamilan ±90–92 hari, melahirkan 1–6 anak. Betina bisa menunda implantasi embrio hingga kondisi lingkungan ideal." },
            { name: "Lemur Ekor Cincin", emoji: "🐾", fact: "Berkomunikasi menggunakan aroma dari kelenjar di pergelangan tangan dan sering berjemur seperti orang meditasi.", diet: "Buah, Daun & Nektar", habitat: "Hutan Madagaskar", reproduksi: "Masa kehamilan ±135 hari, melahirkan 1–2 anak. Musim kawin singkat setahun sekali pada bulan April–Juni." },
            { name: "Rakun", emoji: "🦝", fact: "Terkenal 'mencuci' makanannya di air untuk merangsang indera peraba di tangannya.", diet: "Omnivora", habitat: "Hutan & Perkotaan Amerika Utara", reproduksi: "Masa kehamilan ±63 hari, melahirkan 3–7 anak. Betina mengasuh anak sendirian hingga musim dingin berikutnya." },
            { name: "Kuda Nil", emoji: "🦛", fact: "Meskipun terlihat lamban, kuda nil bisa berlari hingga 30 km/jam di darat.", diet: "Rumput", habitat: "Sungai & Danau Afrika Sub-Sahara", reproduksi: "Masa kehamilan ±240 hari, melahirkan 1 anak di dalam air. Anak langsung bisa berenang setelah lahir." },
            { name: "Kuda Nil Kerdil", emoji: "🦛", fact: "Ukurannya hanya 1/10 kuda nil biasa dan lebih soliter, lebih mirip tapir dari segi perilaku.", diet: "Tumbuhan Air & Rumput", habitat: "Hutan & Rawa Afrika Barat", reproduksi: "Masa kehamilan ±190–210 hari, melahirkan 1 anak. Populasi liar kritis di bawah 2.500 ekor." },
            { name: "Rusa Timor", emoji: "🦌", fact: "Rusa endemik Indonesia yang menjadi mangsa utama predator besar seperti komodo dan harimau.", diet: "Rumput & Daun", habitat: "Hutan & Padang Rumput Indonesia", reproduksi: "Masa kehamilan ±235 hari, melahirkan 1 anak. Jantan dewasa menggugurkan ranggah setiap tahun." },
            { name: "Rusa Bawean", emoji: "🦌", fact: "Satwa endemik yang hanya bisa ditemukan di Pulau Bawean, Jawa Timur.", diet: "Rumput & Daun", habitat: "Hutan Pulau Bawean", reproduksi: "Melahirkan 1 anak. Satwa langka kritis dengan populasi kurang dari 300 ekor di alam liar." },
            { name: "Rusa Sambar", emoji: "🦌", fact: "Rusa terbesar di Asia Tenggara dengan ranggah yang bisa mencapai panjang 1 meter.", diet: "Rumput, Buah & Kulit Pohon", habitat: "Hutan Asia Selatan & Tenggara", reproduksi: "Masa kehamilan ±8 bulan, melahirkan 1 anak. Hidup soliter atau dalam kelompok kecil." },
            { name: "Rusa Tutul", emoji: "🦌", fact: "Bintik putih pada tubuh rusa tutul tetap ada sepanjang hidupnya, berbeda dengan rusa lain.", diet: "Rumput & Dedaunan", habitat: "Hutan India & Sri Lanka", reproduksi: "Masa kehamilan ±235 hari, melahirkan 1–2 anak. Hidup dalam kawanan besar hingga ratusan ekor." },
            { name: "Kambing Gunung Barbary", emoji: "🐐", fact: "Kuku kambing gunung memiliki tepi keras dan bagian dalam lunak, sempurna untuk memanjat tebing.", diet: "Rumput & Tumbuhan Alpine", habitat: "Pegunungan Afrika Utara", reproduksi: "Masa kehamilan ±160 hari, melahirkan 1–2 anak. Anak bisa berdiri dan berlari dalam satu jam setelah lahir." },
            { name: "Eland", emoji: "🦌", fact: "Antelop terbesar di dunia yang bisa melompat pagar setinggi 3 meter meski beratnya hampir 1 ton.", diet: "Rumput & Daun", habitat: "Savana & Hutan Afrika", reproduksi: "Masa kehamilan ±271 hari, melahirkan 1 anak. Anak bisa berdiri dalam 15 menit dan ikut kawanan setelah beberapa jam." },
            { name: "Kijang", emoji: "🦌", fact: "Kijang jantan menggunakan taring, bukan tanduk, untuk bertarung memperebutkan wilayah.", diet: "Daun Muda & Buah", habitat: "Hutan Asia Selatan & Tenggara", reproduksi: "Masa kehamilan ±6 bulan, melahirkan 1–2 anak. Hidup soliter dan sangat pemalu." },
            { name: "Mouflon Eropa", emoji: "🐏", fact: "Leluhur semua domba peliharaan di dunia, berasal dari pegunungan Korsika dan Sardinia.", diet: "Rumput & Semak", habitat: "Pegunungan Mediterania", reproduksi: "Masa kehamilan ±150–160 hari, melahirkan 1–2 anak. Jantan memiliki tanduk melingkar yang terus tumbuh sepanjang hidup." },
            { name: "Sitatunga", emoji: "🦌", fact: "Antelop semi-akuatik yang kuku panjangnya memungkinkan berjalan di atas lumpur rawa.", diet: "Tumbuhan Air & Rawa", habitat: "Rawa & Hutan Riparian Afrika", reproduksi: "Masa kehamilan ±247 hari, melahirkan 1 anak. Betina menyembunyikan anak di vegetasi rapat selama beberapa minggu pertama." },
            { name: "Unta Punuk Satu", emoji: "🐪", fact: "Punuk unta menyimpan lemak, bukan air. Lemak ini bisa diubah menjadi energi dan air saat dibutuhkan.", diet: "Tumbuhan Gurun & Berduri", habitat: "Padang Pasir Asia & Afrika", reproduksi: "Masa kehamilan terlama mamalia darat: ±13 bulan. Melahirkan 1 anak yang bisa berdiri dalam beberapa jam." },
            { name: "Wallabi", emoji: "🦘", fact: "Betina bisa menghentikan sementara perkembangan embrio saat kantung marsupialnya masih terisi.", diet: "Rumput & Tumbuhan", habitat: "Padang Rumput & Hutan Australia", reproduksi: "Masa kehamilan hanya 28–35 hari. Anak (joey) lahir seukuran kacang merah dan berkembang dalam kantung selama 7–10 bulan." },
            { name: "Anoa", emoji: "🐃", fact: "Kerbau terkecil di dunia dan merupakan satwa endemik Sulawesi yang dilindungi.", diet: "Rumput, Pakis & Buah", habitat: "Hutan Sulawesi", reproduksi: "Masa kehamilan ±276 hari, melahirkan 1 anak. Soliter dan sangat sulit dibiakkan di penangkaran." },
            { name: "Banded Mongoose", emoji: "🦡", fact: "Hidup dalam kawanan kooperatif dan secara aktif melindungi sesama dari serangan predator.", diet: "Serangga, Telur & Hewan Kecil", habitat: "Savana & Semak Afrika", reproduksi: "Masa kehamilan ±60–70 hari, melahirkan 2–6 anak. Seluruh anggota kelompok turut menjaga dan merawat anak." },
            { name: "Berang-berang Cakar Kecil", emoji: "🦦", fact: "Tidur mengambang di atas air sambil berpegangan tangan agar tidak terpisah dari pasangannya.", diet: "Ikan & Krustasea", habitat: "Sungai & Danau Asia Tenggara", reproduksi: "Masa kehamilan ±60–65 hari, melahirkan 1–3 anak. Anak belajar berenang pada usia 2 bulan di bawah bimbingan induk." },
            { name: "Gajah Sumatera", emoji: "🐘", fact: "Memiliki ingatan yang luar biasa kuat dan ikatan keluarga yang sangat mendalam.", diet: "Herbivora (Tumbuhan)", habitat: "Hutan & Dataran Rendah Sumatera", reproduksi: "Masa kehamilan ±22 bulan, terlama di antara mamalia darat. Melahirkan 1 anak, dirawat oleh seluruh betina dalam kawanan." },
            { name: "GNU (Wildebeest)", emoji: "🐃", fact: "Setiap tahun, 1,5 juta gnu melakukan migrasi terpanjang mamalia darat di dunia di Afrika Timur.", diet: "Rumput", habitat: "Savana Afrika Timur", reproduksi: "Masa kehamilan ±250 hari. Sekitar 80% betina melahirkan dalam jangka 3 minggu yang sama untuk membanjiri predator." },
            { name: "Jerapah", emoji: "🦒", fact: "Jerapah hanya tidur sekitar 30 menit hingga 2 jam saja dalam sehari!", diet: "Daun Pohon Tinggi", habitat: "Savana Afrika", reproduksi: "Masa kehamilan ±15 bulan, melahirkan 1 anak setinggi 1,8 m. Anak lahir dengan jatuh dari ketinggian ±2 meter dan bisa berdiri dalam 1 jam." },
            { name: "Sugar Glider", emoji: "🐿️", fact: "Mampu meluncur di udara hingga 50 meter menggunakan selaput kulit yang menghubungkan kaki depan dan belakang.", diet: "Nektar, Serangga & Buah", habitat: "Hutan Australia & Papua", reproduksi: "Masa kehamilan hanya 16 hari. Anak (joey) masuk kantung marsupial dan berkembang di sana selama 70–74 hari." }
        ]
    },

    aves: {
        title: "Dunia Aves",
        desc: "Koleksi burung eksotis dengan warna-warni bulu yang memukau.",
        animals: [
            { name: "Bangau Tong-Tong", emoji: "🦢", fact: "Paruhnya yang besar bisa menghasilkan suara klotak keras saat beradu dengan pasangan.", diet: "Ikan, Katak & Mamalia Kecil", habitat: "Rawa & Ladang Asia Selatan–Tenggara", reproduksi: "Bertelur 1–4 butir, inkubasi ±28 hari. Kedua induk bergantian mengerami dan memberi makan anak." },
            { name: "Bayan", emoji: "🦜", fact: "Bayan jantan dan betina memiliki warna bulu yang benar-benar berbeda — merah dan hijau.", diet: "Buah, Biji & Bunga", habitat: "Hutan Kepulauan Maluku & Papua", reproduksi: "Bertelur 2 butir, inkubasi ±26 hari. Bersarang di lubang pohon tinggi, anak diasuh kedua induk." },
            { name: "Beo Nias", emoji: "🐦", fact: "Burung peniru suara terbaik di dunia, mampu menirukan suara manusia dengan sangat akurat.", diet: "Buah & Serangga", habitat: "Hutan Tropis Asia Tenggara", reproduksi: "Bertelur 2–3 butir di lubang pohon. Inkubasi ±13–14 hari oleh betina, anak keluar sarang dalam 4 minggu." },
            { name: "Bilbong Pendeta", emoji: "🐦", fact: "Memiliki bulu kepala hitam mengkilap kontras dengan tubuh putih bersih yang elegan.", diet: "Buah & Serangga", habitat: "Hutan Sulawesi & Maluku", reproduksi: "Bertelur 2–3 butir, inkubasi ±14 hari. Hidup berpasangan setia dan bersarang di lubang pohon." },
            { name: "Elang Bondol", emoji: "🦅", fact: "Kepala dan dada putih kontras dengan sayap merah coklat menjadikannya ikon Kepulauan Seribu Jakarta.", diet: "Ikan, Bangkai & Reptil Kecil", habitat: "Pesisir & Sungai Asia–Australia", reproduksi: "Bertelur 1–3 butir, inkubasi ±26–35 hari. Setia pada pasangan dan sarang yang sama tiap tahun." },
            { name: "Julang Emas", emoji: "🐦", fact: "Jantan memiliki paruh bergerigi emas dan betina diurung di sarang oleh jantan selama mengerami.", diet: "Buah & Hewan Kecil", habitat: "Hutan Kalimantan & Sumatera", reproduksi: "Bertelur 1–2 butir. Betina dikurung dalam lubang pohon selama inkubasi, hanya menerima makanan dari jantan melalui celah." },
            { name: "Flamingo Minor", emoji: "🦩", fact: "Warna merah muda flamingo berasal dari pigmen karotenoid dalam alga yang mereka makan.", diet: "Alga & Krustasea Mikro", habitat: "Danau Asin Afrika & Asia Selatan", reproduksi: "Bertelur 1 butir saja per musim, inkubasi ±28 hari. Kedua induk bergantian mengerami dalam koloni besar." },
            { name: "Gagak Hutan", emoji: "🐦", fact: "Dianggap salah satu burung terpintar di dunia, mampu membuat dan menggunakan alat bantu.", diet: "Omnivora", habitat: "Hutan Boreal & Tundra Belahan Utara", reproduksi: "Bertelur 3–7 butir, inkubasi ±20–21 hari. Betina mengerami, jantan memberi makan betina selama inkubasi." },
            { name: "Kasuari Gelambir Tunggal", emoji: "🦤", fact: "Burung terberat ketiga di dunia dengan cakar mematikan sepanjang 12 cm.", diet: "Buah, Serangga & Hewan Kecil", habitat: "Hutan Hujan Papua & Australia Utara", reproduksi: "Bertelur 3–5 butir hijau besar. Jantan mengerami sendirian selama ±50 hari dan mengasuh anak hingga 9 bulan." },
            { name: "Kasuari Gelambir Dua", emoji: "🦤", fact: "Bulu kasuari mirip rambut karena tidak memiliki barbula pengunci seperti burung biasa.", diet: "Buah Jatuh & Fungi", habitat: "Hutan Hujan Papua Baru & Queensland", reproduksi: "Bertelur 3–8 butir. Seperti kasuari lainnya, jantan bertanggung jawab penuh atas inkubasi dan pengasuhan anak." },
            { name: "Merak Hijau", emoji: "🦚", fact: "Merak hijau jantan memiliki ekor menjuntai hingga 3 meter dan merupakan burung nasional Myanmar.", diet: "Biji, Buah & Serangga", habitat: "Hutan & Padang Rumput Asia Tenggara", reproduksi: "Bertelur 3–6 butir, inkubasi ±28 hari oleh betina. Jantan poligami, menjaga wilayah dan memikat betina dengan tarian." },
            { name: "Nuri Hitam", emoji: "🦜", fact: "Bulunya yang serba hitam mengkilap mencuri perhatian, berbeda dari sebagian besar nuri berwarna cerah.", diet: "Nektar, Buah & Bunga", habitat: "Hutan Kepulauan Maluku", reproduksi: "Bertelur 2 butir di lubang pohon, inkubasi ±24 hari. Kedua induk bergantian merawat anak." },
            { name: "Ibis Putih Kepala Hitam", emoji: "🐦", fact: "Paruhnya yang panjang melengkung digunakan untuk mengorek lumpur mencari mangsa.", diet: "Ikan, Katak & Krustasea", habitat: "Rawa & Sawah Asia Selatan–Tenggara", reproduksi: "Bertelur 3–5 butir, inkubasi ±21–23 hari. Bersarang secara koloni bersama burung air lainnya." },
            { name: "Junai Mas", emoji: "🕊️", fact: "Salah satu merpati tercantik di dunia dengan bulu pelangi berkilau dan kalung merah di leher.", diet: "Biji & Buah", habitat: "Hutan Kepulauan Nicobar & Asia Tenggara", reproduksi: "Hanya bertelur 1 butir per musim. Inkubasi ±30 hari, anak diasuh kedua induk secara bergantian." },
            { name: "Kakatua Jambul Kuning", emoji: "🦜", fact: "Jambul kuning yang bisa berdiri tegak digunakan untuk komunikasi dan ekspresi emosi.", diet: "Biji, Kacang & Buah", habitat: "Hutan Sulawesi & Nusa Tenggara", reproduksi: "Bertelur 2–3 butir, inkubasi ±25–26 hari. Monogami ketat, pasangan saling mempererat ikatan dengan saling mendandani bulu." },
            { name: "Kangkareng Perut Putih", emoji: "🐦", fact: "Seperti kerabat julang, betina dikurung di sarang selama inkubasi dan hanya menerima makanan dari jantan.", diet: "Buah & Hewan Kecil", habitat: "Hutan Asia Selatan & Tenggara", reproduksi: "Bertelur 1–4 butir. Betina menutup diri di rongga pohon dengan lumpur, hanya menyisakan celah kecil untuk makan." },
            { name: "Kakatua Kepala Hitam (Black Capped Lory)", emoji: "🦜", fact: "Warna bulunya adalah perpaduan merah, biru, dan hijau cerah yang sangat memukau.", diet: "Nektar & Buah", habitat: "Hutan Papua & Papua Nugini", reproduksi: "Bertelur 2 butir, inkubasi ±24 hari. Anak tetap di sarang hingga usia 10–12 minggu." },
            { name: "Nuri Kelam", emoji: "🦜", fact: "Gradasi warna bulunya dari oranye ke coklat gelap sangat unik di antara jenis nuri lainnya.", diet: "Nektar & Bunga", habitat: "Hutan Maluku & Papua", reproduksi: "Bertelur 2 butir di lubang pohon. Inkubasi ±24–26 hari, kedua induk berbagi tugas mengeram." },
            { name: "Kepodang", emoji: "🐦", fact: "Suara siulannya yang merdu sangat khas dan sering dijadikan inspirasi musik tradisional Jawa.", diet: "Serangga & Buah", habitat: "Hutan & Taman Asia–Afrika", reproduksi: "Bertelur 2–4 butir, inkubasi ±14–15 hari. Sarangnya berbentuk mangkuk kecil yang dianyam dengan sangat rapi di ujung dahan." },
            { name: "Kowak Merah", emoji: "🐦", fact: "Burung kuntul malam yang aktif berburu ketika sebagian besar burung air lainnya sudah tidur.", diet: "Ikan & Katak", habitat: "Rawa & Danau Australia & Asia", reproduksi: "Bertelur 2–5 butir, inkubasi ±24–26 hari. Bersarang dalam koloni campuran bersama burung air lain." },
            { name: "Kroonkran", emoji: "🦢", fact: "Mahkota emas di kepalanya terbuat dari bulu kaku berwarna emas keemasan yang sangat indah.", diet: "Biji, Serangga & Katak", habitat: "Savana & Rawa Afrika Sub-Sahara", reproduksi: "Bertelur 2–5 butir, inkubasi ±28–31 hari. Pasangan setia seumur hidup, menari bersama sebagai ritual ikatan." },
            { name: "Macaw Merah", emoji: "🦜", fact: "Bisa terbang hingga 700 km per hari dan merupakan simbol hutan tropis Amerika Latin.", diet: "Biji Keras, Buah & Kacang", habitat: "Hutan Hujan Amerika Tengah & Selatan", reproduksi: "Bertelur 1–4 butir, inkubasi ±24–28 hari. Monogami seumur hidup, pasangan selalu terbang dan makan bersama." },
            { name: "Kakatua Maluku", emoji: "🦜", fact: "Jambul merah mudanya yang dramatis bisa berdiri sempurna dan sering disebut kakatua paling cantik.", diet: "Biji, Kacang & Buah", habitat: "Hutan Kepulauan Maluku", reproduksi: "Bertelur 1–2 butir, inkubasi ±28 hari. Terancam punah kritis, populasi alam liar hanya ribuan ekor." },
            { name: "Maleo", emoji: "🐦", fact: "Tidak mengerami telurnya sendiri — mengubur telur di pasir panas atau dekat sumber panas bumi.", diet: "Buah, Biji & Serangga", habitat: "Hutan Sulawesi", reproduksi: "Bertelur 1 butir per 10–12 hari di lokasi penguburan komunal. Anak menetas sendiri dan langsung bisa terbang." },
            { name: "Nuri Merah", emoji: "🦜", fact: "Warna merahnya yang menyala berasal dari pigmen unik yang tidak ditemukan pada burung lain.", diet: "Nektar, Buah & Serbuk Sari", habitat: "Hutan Maluku", reproduksi: "Bertelur 2 butir, inkubasi ±24 hari. Monogami, bersarang di lubang pohon bersama pasangan tetap." },
            { name: "Ayam Mutiara", emoji: "🐔", fact: "Berbintik putih ratusan di seluruh tubuh hitamnya, mirip permata mutiara yang tersebar.", diet: "Biji, Serangga & Umbi", habitat: "Savana & Semak Afrika Sub-Sahara", reproduksi: "Bertelur 6–12 butir per musim, inkubasi ±26–28 hari. Hidup dalam kelompok besar dan bersarang di tanah." },
            { name: "Namdur Coklat", emoji: "🐦", fact: "Jantan membangun gazebo hiasan dari ranting untuk memikat betina, bukan sebagai sarang.", diet: "Buah & Serangga", habitat: "Hutan Papua Nugini & Australia", reproduksi: "Bertelur 1–2 butir, betina mengerami dan mengasuh anak sendirian. Jantan fokus membangun dan menjaga gazebo." },
            { name: "Burung Unta", emoji: "🦤", fact: "Burung terbesar di dunia yang tidak bisa terbang namun bisa berlari hingga 70 km/jam.", diet: "Tumbuhan, Biji & Serangga", habitat: "Savana & Semi-Gurun Afrika", reproduksi: "Bertelur 7–10 butir (telur terbesar di dunia). Jantan alfa dan betina dominan bersama mengerami seluruh telur komunal." },
            { name: "Pelikan", emoji: "🐦", fact: "Kantung paruhnya bisa menampung 13 liter air, tiga kali kapasitas perutnya sendiri.", diet: "Ikan", habitat: "Danau & Pantai Australia", reproduksi: "Bertelur 1–3 butir, inkubasi ±29–36 hari. Bersarang dalam koloni besar di pulau terpencil, anak muda berkumpul dalam 'pod'." },
            { name: "Perkici Pelangi", emoji: "🦜", fact: "Lidahnya memiliki ujung seperti sikat khusus untuk memungut nektar dari bunga.", diet: "Nektar & Serbuk Sari", habitat: "Hutan & Taman Australia–Papua", reproduksi: "Bertelur 2 butir, inkubasi ±23 hari. Betina mengerami sendiri, jantan menjaga wilayah di sekitar sarang." },
            { name: "Ayam Pegar Perak", emoji: "🐦", fact: "Jantan memiliki bulu hitam putih bergaris seperti pola zebra yang sangat mencolok.", diet: "Biji, Serangga & Buah", habitat: "Hutan Pegunungan Asia Tenggara", reproduksi: "Bertelur 6–9 butir, inkubasi ±25 hari oleh betina seorang diri. Jantan menjaga wilayah dengan suara keras." },
            { name: "Poksai Jambul Putih", emoji: "🐦", fact: "Memiliki suara nyanyian yang merdu dan sangat populer sebagai burung peliharaan di Asia.", diet: "Serangga, Buah & Cacing", habitat: "Hutan & Semak Himalaya–Asia Tenggara", reproduksi: "Bertelur 3–5 butir, inkubasi ±13–14 hari. Bersarang di semak rendah, anak meninggalkan sarang dalam 2 minggu." },
            { name: "Kuntul Putih Besar", emoji: "🦢", fact: "Bulu mahkota panjang putih yang indah saat musim kawin pernah hampir membuatnya punah karena diburu.", diet: "Ikan & Katak", habitat: "Rawa & Danau di Seluruh Dunia", reproduksi: "Bertelur 3–4 butir, inkubasi ±23–26 hari. Bersarang dalam koloni besar, kedua induk bergantian menjaga sarang." },
            { name: "Kakatua Raja", emoji: "🦜", fact: "Kakatua terbesar di dunia dengan jambul hitam menjulang dan pipi merah menyala yang dramatis.", diet: "Biji Keras & Buah", habitat: "Hutan Papua & Australia Utara", reproduksi: "Hanya bertelur 1 butir setiap 2 tahun, inkubasi ±30 hari. Pasangan monogami, sarang di lubang pohon besar." },
            { name: "Rangkong Badak", emoji: "🐦", fact: "Tanduk di atas paruhnya berbentuk seperti tanduk badak, menjadi simbol kebanggaan negara Malaysia.", diet: "Buah & Hewan Kecil", habitat: "Hutan Hujan Kalimantan & Sumatera", reproduksi: "Bertelur 1–2 butir. Betina mengurung diri di lubang pohon selama inkubasi ±40 hari, jantan menyuplai makanan." },
            { name: "Ibis Rokoroko", emoji: "🐦", fact: "Bulu kehijauan berkilau menghasilkan kilauan pelangi di bawah sinar matahari yang menakjubkan.", diet: "Cacing, Serangga & Krustasea", habitat: "Rawa, Tambak & Sawah di Seluruh Dunia", reproduksi: "Bertelur 3–4 butir, inkubasi ±21 hari. Bersarang dalam koloni besar bersama bangau dan kuntul lainnya." },
            { name: "Nuri Sayap Hitam", emoji: "🦜", fact: "Kontras warna merah cerah dan hitam pada sayapnya menjadikannya salah satu nuri paling mencolok.", diet: "Nektar & Buah", habitat: "Hutan Kepulauan Maluku", reproduksi: "Bertelur 2 butir di lubang pohon, inkubasi ±24 hari. Kedua induk bergantian merawat anak." },
            { name: "Julang Sulawesi", emoji: "🐦", fact: "Tanduk di paruh jantan berwarna merah dan kuning bergelombang, berbeda dari semua rangkong lainnya.", diet: "Buah & Hewan Kecil", habitat: "Hutan Sulawesi", reproduksi: "Bertelur 1–2 butir. Betina dikurung di sarang selama inkubasi, menerima makanan dari jantan melalui celah kecil." },
            { name: "Poksai Sumatera", emoji: "🐦", fact: "Ciri khas hitam putih kontras dan suara nyanyian merdu menjadikannya burung kicau favorit.", diet: "Serangga & Buah", habitat: "Hutan Sumatera", reproduksi: "Bertelur 2–4 butir, inkubasi ±13 hari. Hidup berpasangan setia, bersarang di semak lebat." },
            { name: "Jalak Suren", emoji: "🐦", fact: "Suaranya yang keras dan beragam bisa menirukan bunyi-bunyian sekitar termasuk suara manusia.", diet: "Serangga, Buah & Cacing", habitat: "Hutan & Area Pertanian Asia Selatan–Tenggara", reproduksi: "Bertelur 4–6 butir biru kehijauan, inkubasi ±12–13 hari. Bersarang di lubang pohon atau celah bangunan." },
            { name: "Takur Api", emoji: "🐦", fact: "Kepala merahnya yang menyala seperti api menjadikannya salah satu burung paling mencolok di hutan.", diet: "Serangga & Buah Kecil", habitat: "Hutan Hujan Kalimantan & Sumatera", reproduksi: "Bertelur 2–4 butir di lubang pohon yang dipahat sendiri. Inkubasi ±13–15 hari oleh kedua induk bergantian." },
            { name: "Kakatua Tanimbar", emoji: "🦜", fact: "Kakatua terkecil di Indonesia yang dikenal cerdas dan lincah meski ukurannya mungil.", diet: "Biji, Kacang & Buah", habitat: "Hutan Kepulauan Tanimbar, Maluku", reproduksi: "Bertelur 2–3 butir, inkubasi ±24 hari. Endemik Pulau Tanimbar, terancam oleh perdagangan ilegal hewan peliharaan." },
            { name: "Tuwur Asia", emoji: "🐦", fact: "Termasuk keluarga burung parasit — betina menyelundupkan telurnya ke sarang burung lain untuk dierami.", diet: "Serangga & Buah", habitat: "Hutan, Taman & Semak Asia–Australia", reproduksi: "Betina tidak pernah membuat sarang sendiri. Telur dititipkan ke sarang inang, anak tuwur dibesarkan oleh induk adopsi." }
        ]
    },

    reptil: {
        title: "Dunia Reptil",
        desc: "Jelajahi makhluk berdarah dingin yang tangguh dan eksotis.",
        animals: [
            { name: "Iguana Merah", emoji: "🦎", fact: "Warna merahnya berasal dari seleksi penangkaran, iguana liar umumnya berwarna hijau.", diet: "Tumbuhan, Buah & Sayuran", habitat: "Amerika Tengah & Selatan (penangkaran)", reproduksi: "Bertelur 10–30 butir per musim, dikubur di tanah. Inkubasi alami ±65–115 hari tergantung suhu lingkungan." },
            { name: "Iguana Hijau", emoji: "🦎", fact: "Berekor panjang yang bisa dilepaskan saat ditangkap predator dan tumbuh kembali.", diet: "Daun, Buah & Bunga", habitat: "Hutan Tropis Amerika Tengah & Selatan", reproduksi: "Bertelur 20–70 butir dalam satu sarang. Betina bisa menyimpan sperma dan bertelur tanpa kawin ulang selama beberapa musim." },
            { name: "Komodo", emoji: "🦎", fact: "Kadal terbesar di dunia yang merupakan kebanggaan satwa asli Indonesia.", diet: "Karnivora", habitat: "Pulau Komodo & Rinca", reproduksi: "Bertelur 15–30 butir di sarang buatan. Uniknya bisa bereproduksi secara partenogenesis tanpa pejantan." },
            { name: "Soa-soa Layar", emoji: "🦎", fact: "Memiliki jambul dan 'layar' di punggung seperti dinosaurus kecil yang bisa berdiri dengan dua kaki.", diet: "Serangga, Ikan & Buah", habitat: "Hutan Hujan & Sungai Maluku–Papua", reproduksi: "Bertelur 4–8 butir di lubang tanah atau dekat sumber air. Inkubasi ±65–80 hari, anak menetas mandiri." },
            { name: "Sanca Bodo Albino", emoji: "🐍", fact: "Merupakan variasi warna langka dari ular piton terbesar di dunia yang sangat diminati kolektor.", diet: "Mamalia Besar & Burung", habitat: "Asia Selatan & Tenggara (penangkaran)", reproduksi: "Bertelur 20–100 butir besar per musim. Betina melingkari telur dan mengejang otot untuk menghasilkan panas." },
            { name: "Sanca Bodo", emoji: "🐍", fact: "Salah satu ular terbesar di dunia, bisa mencapai panjang 9 meter dan berat 130 kg.", diet: "Mamalia Besar & Burung", habitat: "Hutan & Rawa Asia Selatan–Tenggara", reproduksi: "Bertelur 20–100 butir. Betina satu-satunya ular yang menghasilkan panas metabolik untuk mengerami telur." },
            { name: "Ular Sendok Jawa", emoji: "🐍", fact: "Bisa menyemprotkan bisa ke mata musuh dari jarak 3 meter dengan akurasi yang sangat tinggi.", diet: "Katak, Tikus & Ular Kecil", habitat: "Hutan, Sawah & Pemukiman Jawa", reproduksi: "Bertelur 8–30 butir di tanah lembab. Induk terkadang menjaga telur hingga menetas, berbeda dari banyak ular lain." },
            { name: "Ular King Kobra", emoji: "🐍", fact: "Ular berbisa terpanjang di dunia, bisa mencapai 5,5 meter, dan cukup kuat membunuh gajah.", diet: "Ular Lain (Ophiophagus)", habitat: "Hutan Hujan Asia Selatan–Tenggara", reproduksi: "Satu-satunya ular yang membangun sarang untuk telurnya. Bertelur 20–50 butir, betina menjaga sarang dengan agresif." },
            { name: "Kura-kura Red Foot", emoji: "🐢", fact: "Bintik merah terang pada kakinya berfungsi sebagai sinyal komunikasi sesama spesies.", diet: "Buah, Jamur & Bangkai", habitat: "Hutan Amerika Selatan", reproduksi: "Bertelur 2–7 butir per siklus, beberapa kali setahun. Betina mengubur telur di tanah, inkubasi ±150 hari." },
            { name: "Penyu Hijau", emoji: "🐢", fact: "Menempuh ribuan kilometer untuk kembali bertelur tepat di pantai tempat mereka lahir puluhan tahun lalu.", diet: "Lamun & Alga", habitat: "Samudra Tropis & Subtropis", reproduksi: "Bertelur 100–200 butir per musim di pantai berpasir. Betina bertelur setiap 2–4 tahun. Jenis kelamin ditentukan oleh suhu sarang." },
            { name: "Kura-kura Blanding", emoji: "🐢", fact: "Bisa hidup hingga 80 tahun dan terus bisa bereproduksi di usia tua, unik di antara reptil.", diet: "Invertebrata Air & Tumbuhan", habitat: "Danau & Rawa Amerika Utara", reproduksi: "Bertelur 3–19 butir, dikubur di tanah jauh dari air. Inkubasi ±60–80 hari, betina baru matang seksual di usia 14–25 tahun." },
            { name: "Kuya Batok", emoji: "🐢", fact: "Cangkang belakangnya sangat tinggi dan membulat sempurna seperti tempurung (batok) kelapa.", diet: "Buah, Cacing & Serangga", habitat: "Hutan & Rawa Asia Tenggara", reproduksi: "Bertelur 1–3 butir per siklus, beberapa kali dalam setahun. Inkubasi ±60–90 hari, anak menetas mandiri di bawah tanah." },
            { name: "Kura-kura Telinga Merah", emoji: "🐢", fact: "Bercak merah di belakang matanya berfungsi seperti telinga palsu untuk mengecoh predator.", diet: "Omnivora", habitat: "Sungai & Danau Amerika Utara", reproduksi: "Bertelur 4–23 butir per siklus, 2–3 kali setahun. Satu betina bisa bertelur dari beberapa pejantan berbeda dalam satu musim." },
            { name: "Biuku", emoji: "🐢", fact: "Kura-kura air tawar yang hampir punah dan sangat jarang ditemukan di alam liar.", diet: "Tumbuhan Air & Ikan", habitat: "Sungai & Rawa Asia Selatan", reproduksi: "Bertelur 10–30 butir, dikubur di pasir pinggir sungai. Inkubasi ±60–90 hari. Terancam kritis karena hilangnya habitat." },
            { name: "Labi-labi Moncong Babi", emoji: "🐢", fact: "Satu-satunya kura-kura bertubuh lunak bernapas secara kutan (lewat kulit) seperti amfibi.", diet: "Moluska, Krustasea & Buah", habitat: "Sungai & Rawa Papua & Australia Utara", reproduksi: "Bertelur 7–39 butir di pasir pinggir sungai. Inkubasi ±60–80 hari. Unik karena merupakan kura-kura peralihan antara darat dan laut." }
        ]
    },

    pisces: {
        title: "Dunia Pisces",
        desc: "Keanekaragaman hayati bawah air yang menakjubkan.",
        animals: [
            { name: "Gurami Sabah", emoji: "🐟", fact: "Gurami terbesar di dunia yang berekor merah menyala, bisa mencapai panjang 70 cm.", diet: "Tumbuhan Air & Serangga", habitat: "Sungai & Danau Kalimantan", reproduksi: "Jantan membangun sarang busa di permukaan air. Bertelur ratusan butir, jantan menjaga sarang hingga menetas." },
            { name: "Ikan Belida", emoji: "🐟", fact: "Tubuhnya pipih seperti pisau dengan organ listrik lemah untuk navigasi di air keruh.", diet: "Ikan Kecil & Krustasea", habitat: "Sungai Besar Sumatera & Kalimantan", reproduksi: "Bertelur di dasar berlumpur, jantan menjaga telur. Terancam punah akibat penangkapan berlebihan untuk bahan kerupuk." },
            { name: "Nila Merah", emoji: "🐟", fact: "Hasil persilangan beberapa spesies nila, menghasilkan warna merah-oranye yang indah.", diet: "Alga & Plankton", habitat: "Kolam & Sungai Tropis", reproduksi: "Betina adalah mouthbrooder: mengerami telur dan burayak di dalam mulut selama ±4 minggu." },
            { name: "Peacock Bass Monoculus", emoji: "🐟", fact: "Ikan bass yang sangat agresif dengan bintik mirip 'mata melek' di ekornya untuk mengecoh predator.", diet: "Ikan Kecil", habitat: "Sungai Amazon & Amerika Selatan", reproduksi: "Pasangan membersihkan substrat keras untuk tempat bertelur. Kedua induk menjaga telur dan burayak secara aktif." },
            { name: "Ikan Aligator", emoji: "🐟", fact: "Ikan purba dengan moncong mirip buaya dan sisik tebal seperti lapisan baja, fosil hidup sejati.", diet: "Ikan & Hewan Kecil", habitat: "Sungai & Danau Amerika Selatan", reproduksi: "Bertelur di vegetasi air yang lebat. Telur berwarna merah tua dan beracun bagi mamalia, tapi aman bagi ikan lain." },
            { name: "Ikan Kaos Kaki", emoji: "🐟", fact: "Corak pita hitam vertikal di tubuhnya menyerupai motif kaos kaki bergaris khas.", diet: "Serangga & Cacing", habitat: "Sungai Tropis Asia Tenggara", reproduksi: "Bertelur di lubang substrat atau akar pohon. Jantan menjaga dan mengipasi telur dengan sirip hingga menetas." },
            { name: "Red-Head Synspilum", emoji: "🐟", fact: "Kepala merahnya yang dramatis kontras dengan tubuh biru-hijau berkilau, menjadikannya ikan hias populer.", diet: "Tumbuhan Air & Invertebrata", habitat: "Sungai Amerika Tengah", reproduksi: "Membersihkan permukaan keras untuk bertelur. Pasangan menjaga wilayah sarang dengan sangat agresif." },
            { name: "Ikan Genghis Khan (Giant Pangasius)", emoji: "🐟", fact: "Lele raksasa yang bisa mencapai 3 meter dan 300 kg, salah satu ikan air tawar terbesar di dunia.", diet: "Alga & Buah Jatuh", habitat: "Sungai Mekong & Asia Tenggara", reproduksi: "Bermigrasi ribuan km untuk bertelur di hulu sungai. Terancam kritis, populasi liar kurang dari beberapa ratus ekor." },
            { name: "Damsel Ekor Kuning", emoji: "🐠", fact: "Ekor kuning cerahnya berfungsi sebagai sinyal waspada kepada sesama ikan saat predator mendekat.", diet: "Alga & Plankton", habitat: "Terumbu Karang Indo-Pasifik", reproduksi: "Jantan mempersiapkan substrat dan menarik betina untuk bertelur. Telur dijaga jantan hingga menetas dalam ±3 hari." },
            { name: "Kakap Tompel", emoji: "🐠", fact: "Bintik hitam di tubuhnya mirip bekas tompel, memberi kamuflase saat bersembunyi di terumbu.", diet: "Ikan Kecil & Krustasea", habitat: "Terumbu Karang Indo-Pasifik", reproduksi: "Pemijah agregat — berkumpul ratusan individu untuk memijah bersamaan saat bulan purnama di tepi terumbu." },
            { name: "Ikan Keling Tanduk", emoji: "🐠", fact: "Bergerak dengan cara menggali pasir dan berguling seperti batu karang untuk bersembunyi.", diet: "Invertebrata Dasar Laut", habitat: "Terumbu Karang Indo-Pasifik", reproduksi: "Memijah di kolom air terbuka. Sel telur dan sperma dilepas bersamaan, fertilisasi terjadi di luar tubuh secara eksternal." },
            { name: "Ikan Betok Zebra", emoji: "🐠", fact: "Pola garis zebra vertikalnya membantu menyamarkan diri di sela-sela terumbu karang yang ramai.", diet: "Alga & Plankton", habitat: "Terumbu Karang Indo-Pasifik", reproduksi: "Jantan menjaga wilayah alga kecil sebagai 'kebun' untuk menarik betina bertelur. Telur dijaga jantan agresif." },
            { name: "Baronang", emoji: "🐟", fact: "Sirip punggungnya yang sangat tajam mengandung kelenjar racun sebagai mekanisme pertahanan.", diet: "Alga & Rumput Laut", habitat: "Terumbu Karang & Padang Lamun Indo-Pasifik", reproduksi: "Memijah secara massal saat musim kawin. Telur dan larva melayang bebas di perairan terbuka (planktonis)." },
            { name: "Ikan Keling Kuning", emoji: "🐠", fact: "Warna kuning cemerlangnya yang rata di seluruh tubuh menjadikannya salah satu ikan hias terindah.", diet: "Invertebrata Kecil & Alga", habitat: "Terumbu Karang Indo-Pasifik", reproduksi: "Ikan pelagik pemijah: melepaskan telur dan sperma di kolom air terbuka. Larva melayang jauh sebelum menetap di terumbu." },
            { name: "Ikan Letter 6 (Foxface)", emoji: "🐠", fact: "Pola hitam putih di wajahnya berbentuk angka 6, fungsinya untuk mengecoh predator.", diet: "Alga & Spons", habitat: "Terumbu Karang Indo-Pasifik", reproduksi: "Memijah berpasangan di kolom air terbuka saat senja. Telur planktonis menetas dalam 24 jam di laut terbuka." },
            { name: "Ikan Kepe-kepe", emoji: "🐠", fact: "Bintik hitam besar di dekat ekornya menyerupai mata, membuat predator salah mengira arah lari.", diet: "Polip Karang & Invertebrata", habitat: "Terumbu Karang Indo-Pasifik", reproduksi: "Memijah berpasangan setia yang jarang berganti pasangan. Telur dilepas di kolom air, larva menetap di terumbu setelah beberapa minggu." },
            { name: "Hiu Karang Sirip Hitam", emoji: "🦈", fact: "Ujung siripnya yang berwarna hitam menjadi tanda pengenal yang paling ikonik di perairan dangkal.", diet: "Ikan & Krustasea", habitat: "Terumbu Karang Indo-Pasifik", reproduksi: "Vivipar (melahirkan). Masa kehamilan ±9–11 bulan, melahirkan 2–5 anak yang langsung bisa berenang mandiri." },
            { name: "Kerapu Sunuk", emoji: "🐟", fact: "Tubuhnya dihiasi bintik-bintik seperti bulu macan tutul, menjadikannya ikan karang paling mencolok.", diet: "Ikan Kecil & Krustasea", habitat: "Terumbu Karang Indo-Pasifik", reproduksi: "Hermaprodit protoginis: lahir sebagai betina, lalu berubah menjadi jantan saat dewasa. Memijah dalam agregat musiman." },
            { name: "Ikan Kapiat", emoji: "🐟", fact: "Sisiknya yang berkilau seperti timah foil di bawah sinar matahari menjadikannya ikan akuarium yang memesona.", diet: "Tumbuhan Air & Alga", habitat: "Sungai & Danau Asia Tenggara", reproduksi: "Memijah secara massal di musim hujan. Bertelur di vegetasi air yang lebat, telur menempel pada tanaman akuatik." }
        ]
    }
};

let currentActiveKey = '';

function openCategory(key) {
    currentActiveKey = key;
    const data = zooData[key];

    document.getElementById('cat-title').innerText = data.title;
    document.getElementById('cat-desc').innerText = data.desc;

    const container = document.getElementById('animal-list');
    container.innerHTML = '';

    data.animals.forEach(animal => {
        const card = document.createElement('div');
        card.className = "animal-card p-8 rounded-[2.5rem] text-center shadow-lg border-2 border-amber-50";
        card.onclick = () => showDetail(animal);
        card.innerHTML = `
            <div class="text-7xl mb-5">${animal.emoji}</div>
            <div class="font-title text-amber-900 text-xl tracking-wide">${animal.name.toUpperCase()}</div>
        `;
        container.appendChild(card);
    });

    switchView('category-page');
}

function showDetail(animal) {
    document.getElementById('detail-name').innerText = animal.name.toUpperCase();
    document.getElementById('detail-emoji').innerText = animal.emoji;
    document.getElementById('detail-fact').innerText = `"${animal.fact}"`;
    document.getElementById('detail-diet').innerText = animal.diet;
    document.getElementById('detail-habitat').innerText = animal.habitat;
    document.getElementById('detail-reproduksi').innerText = animal.reproduksi;

    const headerColor = document.getElementById('detail-header-color');
    const themeColors = {
        mamalia: 'bg-green-400',
        aves: 'bg-blue-300',
        reptil: 'bg-orange-400',
        pisces: 'bg-blue-600'
    };
    headerColor.className = `absolute top-0 left-0 w-full h-5 ${themeColors[currentActiveKey]}`;

    switchView('detail-page');
}

function switchView(id) {
    document.querySelectorAll('.page-layer').forEach(page => {
        page.classList.remove('active');
    });

    if (id !== 'home') {
        document.getElementById(id).classList.add('active');
    }

    window.scrollTo(0, 0);
}

function goBack(targetId) {
    switchView(targetId);
}